### ISSUE TITLE
Data not processed by the UA-Cloud-Twin

### ISSUE THREAD

**Issue by Sdelausnay** [digitaltwinconsortium/ManufacturingDTDLOntologies#23]
I have installed everything locally on the VM, namely the simulator script and logs tell that "Production lines started". 

If I go and look at EventHub, I see data coming in for both "data" and "metadata" topic. 

![image](https://github.com/digitaltwinconsortium/ManufacturingOntologies/assets/62655804/68348a2e-2dfe-4b87-b099-7d9fed82fcde)

But when I check the UA-Cloud-Twin, it is not processing any data? It has seen meta data information, but it is not processing any other messages. Did I missed something during installation? 

![image](https://github.com/digitaltwinconsortium/ManufacturingOntologies/assets/62655804/c81c535d-ef5f-4fbb-833a-320349ec4247)

Checking the digital gives some things have been created in the twin graph, but don't think this is complete? Making the ADX dashboard is not giving any values. 

![image](https://github.com/digitaltwinconsortium/ManufacturingOntologies/assets/62655804/9ce6d761-103b-49be-b613-f4baa223855b)

**Comment by barnstee** [comment]
Hi Steven, I can see from the discovered assets that the Munich production line is missing in UA Cloud Twin. it looks like there is a problem with the OPC UA certificate exchange that happens with the Azure Storage. I've seen this happen once since I switched to a slower VM (but a lot cheaper VM!). I will increase the pauses between starting the individual parts of the simulation. Please Stop and then Start the production line using the batch scripts on the VM one more time, that should fix it. Also, it is normal that the UA Cloud Twin no longer processes telemetry data, only metadata. This was another cost optimization I made, so telemetry is sent to ADX only now.

**Comment by Sdelausnay** [comment]
Hi, Thanks for the quick response.

Indeed the waiting time was the issue. I saw the waiting "press a key to continue" and didn't wanted to wait :) 
Ok now I also understand better how the data flow is working so ADT is purely for modeling and all telemetry data is stored in ADX and quired in that way. 

Sorry for the question, was a bit to unpetitioned to get everything up and running. 

Very nice demo! Really interesting to see how quickly you can build these dashboards.

**Comment by barnstee** [comment]
Any time, my friend. Let me know what you think of the solution! :-) Also, if you really, really want to have ADT process the telemetry to get a digital twin per OPC UA node which is updated all the time, you can set the environment variable PROCESS_TELEMETRY_MESSAGES to 1 and the behavior will be as it was before.
